import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — Hearth',
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-lg py-3xl">
      <Link
        href="/"
        className="mb-xl inline-block font-sans text-sm text-text-secondary transition-colors hover:text-text-primary"
      >
        &larr; Back to Hearth
      </Link>

      <h1 className="mb-lg font-serif text-3xl font-semibold text-text-primary">
        Terms of Service
      </h1>
      <p className="mb-xl font-sans text-sm text-text-tertiary">
        Last updated: 26 April 2026
      </p>

      <div className="space-y-lg font-serif text-base leading-relaxed text-text-secondary">
        <section>
          <h2 className="mb-sm font-serif text-xl font-semibold text-text-primary">1. Acceptance of Terms</h2>
          <p>
            By creating a Hearth account or otherwise using the Service, you confirm you have read,
            understood, and agree to these Terms of Service and our{' '}
            <Link href="/privacy" className="text-ember underline">
              Privacy Policy
            </Link>
            . If you do not agree, please do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="mb-sm font-serif text-xl font-semibold text-text-primary">2. Alpha pilot status</h2>
          <p>
            Hearth is currently operating as an <strong>invite-only alpha pilot</strong> for a small
            number of Australian homeschool families. The Service is being actively developed:
          </p>
          <ul className="mt-xs ml-md list-disc space-y-xs">
            <li>You may encounter bugs, downtime, or features that change without notice.</li>
            <li>
              We may need to migrate or, in rare cases, reset data to ship a structural change. If we
              do, you will receive notice in advance and an opportunity to export your data first
              (see the Privacy Policy §8 for export details).
            </li>
            <li>
              Reports generated by Hearth — including any Australian Curriculum or Home Education Unit
              (HEU) export — are intended to <em>support</em> your compliance work, not replace your
              judgement. Cross-check before submitting to a regulator.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-sm font-serif text-xl font-semibold text-text-primary">3. Description of Service</h2>
          <p>
            Hearth is a learning management platform designed to help Australian homeschool families
            log, reflect on, and report their children&apos;s education. The Service includes
            retrospective learning logs, curriculum-aligned reporting, capability tracking, badge
            assessments, and a content library of modules and activities curated for homeschool use.
          </p>
        </section>

        <section>
          <h2 className="mb-sm font-serif text-xl font-semibold text-text-primary">4. Membership and content</h2>
          <p>
            All learning content available within Hearth — modules, activities, packs, capability
            threads — is included with your membership at no additional charge. There are no in-app
            purchases, no upsells, and no ads. If we ever introduce paid tiers, we will give existing
            pilot members notice and an opportunity to choose before any change takes effect.
          </p>
        </section>

        <section>
          <h2 className="mb-sm font-serif text-xl font-semibold text-text-primary">5. User accounts</h2>
          <p>
            You are responsible for maintaining the security of your account credentials, including
            any co-facilitator (editor or viewer) accounts you invite to your family. You agree to
            provide accurate information when creating an account and to keep it up to date. The
            family owner is responsible for ensuring all family members consent to having their
            information stored within the family workspace.
          </p>
        </section>

        <section>
          <h2 className="mb-sm font-serif text-xl font-semibold text-text-primary">6. Acceptable use</h2>
          <p>
            You agree not to misuse the Service, including: attempting to gain unauthorised access,
            interfering with other users, using automation to scrape or overload the Service, or using
            it for unlawful purposes. We reserve the right to apply rate limits to protect the Service
            from anomalous usage.
          </p>
        </section>

        <section>
          <h2 className="mb-sm font-serif text-xl font-semibold text-text-primary">7. Intellectual property</h2>
          <p>
            All design, code, and curated content comprising the Service remain the property of Hearth
            Learning Pty Ltd. Content you create — learning log entries, learner profiles, photos,
            facilitator notes, and similar — remains yours. You grant us a limited licence to store,
            display, and process that content solely as needed to operate the Service for you.
          </p>
        </section>

        <section>
          <h2 className="mb-sm font-serif text-xl font-semibold text-text-primary">8. Limitation of liability</h2>
          <p>
            The Service is provided <strong>&quot;as is&quot;</strong> without warranties of any kind.
            To the maximum extent permitted by Australian Consumer Law, Hearth shall not be liable
            for any indirect, incidental, or consequential damages arising from your use of, or
            inability to use, the Service. Nothing in these Terms excludes or limits any consumer
            guarantee that cannot lawfully be excluded.
          </p>
        </section>

        <section>
          <h2 className="mb-sm font-serif text-xl font-semibold text-text-primary">9. Termination</h2>
          <p>
            You may terminate your account at any time via Settings → Account, which calls{' '}
            <code className="rounded-sm bg-surface-raised px-xs py-[1px] font-mono text-[12px]">/api/account/delete</code>{' '}
            after explicit confirmation. We may suspend or terminate access if you breach these
            Terms; we will give notice and a reasonable opportunity to remedy where practical.
          </p>
        </section>

        <section>
          <h2 className="mb-sm font-serif text-xl font-semibold text-text-primary">10. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. Material changes will be announced in-app
            and via email at least 14 days before they take effect. Continued use of the Service
            after changes take effect constitutes acceptance of the revised Terms.
          </p>
        </section>

        <section>
          <h2 className="mb-sm font-serif text-xl font-semibold text-text-primary">11. Governing law</h2>
          <p>
            These Terms are governed by the laws of Queensland, Australia. Any dispute will be heard
            in the courts of Queensland.
          </p>
        </section>

        <section>
          <h2 className="mb-sm font-serif text-xl font-semibold text-text-primary">12. Contact</h2>
          <p>
            Questions about these Terms? Reach us at{' '}
            <a href="mailto:hello@hearthlearning.au" className="text-ember underline">
              hello@hearthlearning.au
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
