import { defineType, defineField } from 'sanity';

export const PRACTICE_KEYS = [
  { title: 'Short, Focused Lessons', value: 'short-lessons' },
  { title: 'Extended Projects', value: 'extended-projects' },
  { title: 'Living Books & Literature', value: 'living-books' },
  { title: 'Hands-On Materials', value: 'hands-on' },
  { title: 'Narration & Discussion', value: 'narration' },
  { title: 'Nature Journaling', value: 'nature-journaling' },
  { title: 'Movement Integration', value: 'movement' },
  { title: 'Daily & Weekly Rhythms', value: 'rhythm' },
  { title: 'Documentation & Portfolios', value: 'documentation' },
  { title: 'Unstructured Play Time', value: 'free-play' },
  { title: 'Memory Work & Recitation', value: 'memory-work' },
  { title: 'Copywork & Handwriting', value: 'copywork' },
] as const;

export const methodologyOverlay = defineType({
  name: 'methodologyOverlay',
  title: 'Methodology Overlay',
  type: 'object',
  description:
    'Per-practice overlay generated by the Kindler at content time. Spec: docs/hearth-methodology-overlay-bundle-v1.md.',
  fields: [
    defineField({
      name: 'practiceKey',
      title: 'Practice Key',
      type: 'string',
      validation: (r) => r.required(),
      options: { list: [...PRACTICE_KEYS] },
    }),
    defineField({
      name: 'loggerPromptHint',
      title: 'Logger Prompt Hint',
      description: '12–20 words. Practice-specific prompt in the Logger description strip.',
      type: 'string',
    }),
    defineField({
      name: 'prepHint',
      title: 'Prep Hint',
      description: '35–60 words. "How you might do this" guidance in Module Experience Prep.',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'observationCue',
      title: 'Observation Cue',
      description: '12–20 words. What this practice trains the parent to notice.',
      type: 'string',
    }),
    defineField({
      name: 'evidenceTagBias',
      title: 'Evidence Tag Bias',
      description: 'Up to 4 capability thread keys this practice tends to surface.',
      type: 'array',
      of: [{ type: 'string' }],
      validation: (r) => r.max(4),
    }),
    defineField({
      name: 'corpusChunkIds',
      title: 'Corpus Chunk Ids',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({ name: 'generatedAt', title: 'Generated At', type: 'datetime' }),
    defineField({ name: 'generatedBy', title: 'Generated By', type: 'string' }),
  ],
  preview: {
    select: { title: 'practiceKey' },
    prepare: ({ title }) => ({ title: title ?? 'methodologyOverlay' }),
  },
});
