import { defineType, defineField } from 'sanity';

export const pedagogyLensBundle = defineType({
  name: 'pedagogyLensBundle',
  title: 'Pedagogy Lens Bundle',
  type: 'object',
  description:
    'Per-pedagogy bundle generated by the Kindler at content time. Spec: docs/hearth-pedagogy-lens-bundle-v1.md.',
  fields: [
    defineField({
      name: 'pedagogyKey',
      title: 'Pedagogy Key',
      type: 'string',
      validation: (r) => r.required(),
      options: {
        list: [
          { title: 'Charlotte Mason', value: 'charlotte_mason' },
          { title: 'Classical', value: 'classical' },
          { title: 'Montessori', value: 'montessori' },
          { title: 'Waldorf / Steiner', value: 'waldorf_steiner' },
          { title: 'Unschooling', value: 'unschooling' },
          { title: 'Eclectic', value: 'eclectic' },
        ],
      },
    }),
    defineField({
      name: 'whyThisMatters',
      title: 'Why This Matters',
      description: '90–120 words. Module-specific framing in this tradition.',
      type: 'text',
      rows: 6,
    }),
    defineField({
      name: 'facilitationNote',
      title: 'Facilitation Note',
      description: '2–3 sentences. What the parent in this tradition actually does during this activity.',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'observationCues',
      title: 'Observation Cues',
      description: 'Up to 3 single-sentence cues drawn from Observational Markers.',
      type: 'array',
      of: [{ type: 'string' }],
      validation: (r) => r.max(3),
    }),
    defineField({
      name: 'questionOverlay',
      title: 'Question Overlay',
      description:
        'What to notice on the next encounter with THIS SAME MODULE\'s content. Within-module scope only — no cross-module forward prescription (per C-PA4, 2026-05-13). Grammar-shaped per pedagogy; runtime renders per pedagogy grammar.',
      type: 'object',
      fields: [
        { name: 'grammar', type: 'string' },
        { name: 'payload', type: 'text', rows: 4 },
      ],
    }),
    defineField({
      name: 'evidencePriorities',
      title: 'Evidence Priorities',
      description: 'Up to 5 capability threads with one-line interpretation.',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'threadKey', type: 'string' },
            { name: 'weight', type: 'number' },
            { name: 'interpretation', type: 'string' },
          ],
        },
      ],
      validation: (r) => r.max(5),
    }),
    defineField({
      name: 'corpusChunkIds',
      title: 'Corpus Chunk Ids',
      description: 'Provenance — admin-only.',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({ name: 'generatedAt', title: 'Generated At', type: 'datetime' }),
    defineField({ name: 'generatedBy', title: 'Generated By', type: 'string' }),
  ],
  preview: {
    select: { title: 'pedagogyKey' },
    prepare: ({ title }) => ({ title: title ?? 'pedagogyLensBundle' }),
  },
});
