import type { MetadataRoute } from 'next';

// Web app manifest. This is the install contract for both the browser PWA and
// the Play Store TWA, so the values here are load-bearing beyond the web —
// see docs/hearth-native-app-plan-v1.md.
//
// Icons are generated by scripts/generate-app-icons.mjs. Every icon is square
// and fully opaque; `any` and `maskable` are separate assets because the source
// mark runs to the edge and would be clipped by Android's circle crop.
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: '/',
    name: 'Hearth',
    short_name: 'Hearth',
    description: 'Homeschool learning management for Australian families',
    start_url: '/',
    // `/` redirects signed-in families onward to welcome / onboarding /
    // dashboard, so it is the correct entry point for every account state.
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    lang: 'en-AU',
    dir: 'ltr',
    categories: ['education', 'productivity'],
    // v2 surface-body. The previous value (#0F0D0B) was the superseded v1
    // token, so the splash screen did not match the app it opened into.
    background_color: '#15110D',
    theme_color: '#15110D',
    icons: [
      {
        src: '/icons/icon-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/maskable-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'maskable',
      },
      {
        src: '/icons/maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
    shortcuts: [
      {
        name: 'Quick Log',
        short_name: 'Log',
        description: 'Capture what your child learned',
        url: '/log',
        icons: [{ src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' }],
      },
      {
        name: 'Dashboard',
        short_name: 'Home',
        description: 'This week at a glance',
        url: '/dashboard',
        icons: [{ src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' }],
      },
    ],
    // `screenshots` is deliberately absent until Phase 4 produces real device
    // captures. Declaring entries that point at files which do not exist is the
    // bug this manifest previously shipped.
  };
}
