/**
 * Hearth PKB — Corpus Review Manifest
 *
 * Read-only. Lists every vault entry still awaiting human review
 * (`suggestedDraft: true`), grouped by framework and layer, with a
 * clickable file path, a title-ish field, and tags — so reviewing the
 * queue doesn't require opening every file in `corpus/pedagogy/` by hand.
 * Never writes to the vault; only regenerates its own manifest file.
 *
 * Run:   npm run corpus:review
 * Next:  npm run corpus:confirm -- --ids <comma,separated,ids>
 */

import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';
import { compileVault, FRAMEWORKS, LAYER_DIRS, frameworkByDir, DEFAULT_VAULT_ROOT } from '../src/lib/pedagogy/corpus';
import { toResolvableDocs, type ResolvableDoc } from '../src/lib/pedagogy/corpus-review/resolve-id';
import { locateVaultFile } from '../src/lib/pedagogy/corpus-review/locate-file';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const OUTPUT_PATH = path.join('.claude', 'plans', 'corpus-fanout', 'review-queue.md');

/** Best available title-ish field, per the doc's layer. */
function titleIsh(doc: Record<string, unknown>): string {
  if (typeof doc.triggerTitle === 'string' && doc.triggerTitle.trim()) return doc.triggerTitle.trim();
  if (typeof doc.markerName === 'string' && doc.markerName.trim()) return doc.markerName.trim();
  if (typeof doc.warnedAgainst === 'string' && doc.warnedAgainst.trim()) return doc.warnedAgainst.trim();

  const snippetSource =
    typeof doc.scenario === 'string' ? doc.scenario : typeof doc.text === 'string' ? doc.text : undefined;
  if (snippetSource) {
    const clean = snippetSource.replace(/\s+/g, ' ').trim();
    return clean.length > 60 ? `${clean.slice(0, 60)}…` : clean;
  }

  // facilitation-vocabulary singleton carries none of the above.
  return '(facilitation vocabulary — see file)';
}

function tagsIsh(doc: Record<string, unknown>): string {
  return Array.isArray(doc.tags) && doc.tags.length > 0 ? doc.tags.join(', ') : '—';
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|');
}

function run() {
  const output = compileVault();
  const pending = output.docs.filter((d) => d.suggestedDraft === true);
  const resolvable = toResolvableDocs(pending);

  const byFrameworkDir = new Map<string, Map<string, ResolvableDoc[]>>();
  for (const entry of resolvable) {
    const framework = FRAMEWORKS.find((f) => f.short === entry.frameworkShort);
    const frameworkDir = framework?.dir ?? entry.frameworkShort;
    if (!byFrameworkDir.has(frameworkDir)) byFrameworkDir.set(frameworkDir, new Map());
    const byLayer = byFrameworkDir.get(frameworkDir)!;
    if (!byLayer.has(entry.layerDir)) byLayer.set(entry.layerDir, []);
    byLayer.get(entry.layerDir)!.push(entry);
  }

  const lines: string[] = [];
  lines.push('# Corpus review queue');
  lines.push('');
  lines.push(
    'Vault entries awaiting human confirmation (`suggestedDraft: true`). Regenerated by ' +
      '`npm run corpus:review` — do not hand-edit, it will be overwritten on the next run.'
  );
  lines.push('');
  lines.push('Confirm with `npm run corpus:confirm -- --ids <comma,separated,ids>` (the `id` column below).');
  lines.push('');

  const frameworkDirsInOrder = [...byFrameworkDir.keys()].sort();

  if (frameworkDirsInOrder.length === 0) {
    lines.push('Nothing pending — every compiled entry is already published + confirmed.');
    lines.push('');
  }

  for (const frameworkDir of frameworkDirsInOrder) {
    const framework = frameworkByDir(frameworkDir);
    const byLayer = byFrameworkDir.get(frameworkDir)!;
    lines.push(`## ${framework?.title ?? frameworkDir}`);
    lines.push('');

    for (const layerDir of LAYER_DIRS) {
      const entries = byLayer.get(layerDir);
      if (!entries || entries.length === 0) continue;

      lines.push(`### ${layerDir} (${entries.length})`);
      lines.push('');
      lines.push('| id | file | title-ish | tags |');
      lines.push('|---|---|---|---|');

      for (const entry of [...entries].sort((a, b) => a.shortId.localeCompare(b.shortId))) {
        const filePath = locateVaultFile(DEFAULT_VAULT_ROOT, frameworkDir, layerDir, entry.shortId);
        const relPath = filePath ? path.relative(process.cwd(), filePath) : '(file not found)';
        lines.push(
          `| \`${entry.qualifiedId}\` | \`${relPath}\` | ${escapeCell(titleIsh(entry.doc))} | ${escapeCell(tagsIsh(entry.doc))} |`
        );
      }
      lines.push('');
    }
  }

  const frameworkCount = frameworkDirsInOrder.length;
  const summary = `${pending.length} entr${pending.length === 1 ? 'y' : 'ies'} pending review across ${frameworkCount} framework${frameworkCount === 1 ? '' : 's'}`;

  lines.push('---');
  lines.push('');
  lines.push(summary);
  lines.push('');

  const markdown = lines.join('\n');

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, markdown, 'utf8');

  console.log(`\nHearth PKB corpus review manifest\n`);
  console.log(markdown);
  console.log(`Written to ${OUTPUT_PATH}`);
  console.log(`\n${summary}`);
}

run();
